Robotis-v0:
  normalize: true
  policy: 'MlpPolicy'
  n_timesteps: !!float 5e6
  n_envs: 4
  batch_size: 64
  n_steps: 512
  gamma: 0.9999
  learning_rate: 0.00017600944889937804
  ent_coef: 0.02922768274743029
  clip_range: 0.1
  n_epochs: 5
  gae_lambda: 0.92
  max_grad_norm: 0.6
  vf_coef : 0.3538047875240017
  sde_sample_freq: -1
  # lr_schedule: constant
  policy_kwargs: "dict(log_std_init=-2.1724770721716666,
                       ortho_init=False,
                       activation_fn=nn.ReLU,
                       net_arch=dict(pi=[256, 256], vf=[256, 256])
                  )"




