DarwinOp3-v3:
  normalize: "dict(norm_obs=True, norm_reward=True)"
  # n_envs: 8
  # # n_timesteps: !!float 5e7
  # callback: 
  #   - robofei.env.callbacks.TensorboardCallback
  policy: 'MlpPolicy'
  learning_starts: 10000
  noise_type: 'normal'
  noise_std: 0.1
  train_freq: 1
  gradient_steps: 1
  learning_rate: !!float 1e-3
  batch_size: 256
  policy_kwargs: "dict(net_arch=[400, 300])"